Add new packages for sorting icons
internetarchive/iaux-icons pull request #15
Opened 2021-05-10 18:16 UTC by dualcnhq

### Changes:

- add sort descending and sort ascending icons

### To Test:

- pull down repo -> go to directory: packages/ia-icons
- in packages/ia-icons directory, run command in-terminal: npm install && npm start
- local server pops up with icon list (random colors generated)
- you should see sortAscending and sortDescending icon in the list when you hover to it 

### On first load look:
<img width="223" alt="Screen Shot 2021-05-22 at 1 40 12 AM" src="https://user-images.githubusercontent.com/1281581/119177441-e84ea780-ba9e-11eb-90ac-746d44b8c241.png">

### On mouse-hover look:
<img width="99" alt="Screen Shot 2021-05-22 at 1 42 26 AM" src="https://user-images.githubusercontent.com/1281581/119177505-fdc3d180-ba9e-11eb-9ad9-24f22c21217a.png">
<img width="102" alt="Screen Shot 2021-05-22 at 1 42 19 AM" src="https://user-images.githubusercontent.com/1281581/119177510-fef4fe80-ba9e-11eb-8c67-e570802bf4d3.png">

2021-05-11 20:26 UTC, iisa requested changes
Hi @dualcnhq, code looks good, we just need a few extra lines at the end of files.

Problem: build is failing, looks like the package was not deployed to NPM.  We should fix this before merge.

Q: are we initially starting versioning at 1.0.0?

Housekeeping:
(this is standard for all PRs to help bring context for the reviewer)
- please update the Description section with what this PR holds, including a screenshot of the added icons.
- please add a ticket in Jira to encompass work to link them, I did not see them on this board.  This way, it is assured that you get the needed code review.

Thanks a bunch.

2021-05-11 20:26 UTC, iisa commented on packages/icon-sort-ascending/icon-sort-ascending.js
> +export default IAIconSortAscending;
let's add a new line ^_^

2021-05-11 20:26 UTC, iisa commented on packages/icon-sort-descending/icon-sort-descending.js
> +export default IAIconSortDescending;
new line at EOF here as well

2021-05-11 20:26 UTC, iisa commented on packages/icon-sort-descending/sort-descending.svg
> +<svg height="18" viewBox="0 0 18 18" width="18" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="m2.32514544 8.30769231.7756949-2.08468003h2.92824822l.75630252 2.0846800
here, too ^_^

2021-05-11 20:26 UTC, iisa commented on packages/ia-icons/package.json
> +    "@internetarchive/icon-sort-descending": "^1.2.2",
Q: is this the start of the packages versioning?

2021-05-12 01:37 UTC, dualcnhq commented on packages/ia-icons/package.json
> +    "@internetarchive/icon-sort-descending": "^1.2.2",
this was auto-generated from the code for some reason... will double check/update it if possible

2021-05-14 22:16 UTC, jbuckner commented on packages/icon-sort-ascending/index.js
> +<svg height="18" viewBox="0 0 18 18" width="18" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="m2.32514544 8.30769231.7756949-2.08468003h2.92824822l.75630252 2.0846800
Something we've been doing with these icons is adding `class="fill-color"` to the outermost `<g>` element to make them customizable with CSS variables (see [this one](https://github.com/internetarchive/iaux-icons/blob/master/packages/icon-calendar/index.js#L8)). That's what [those CSS variables](https://github.com/internetarchive/iaux-icons/pull/15/files#diff-d456ea5300ea0e069c574cfd357b79f3cc950de2278a4c046b0ef76e8dfe66ceR13) are for in the actual icon.

2021-05-14 22:22 UTC, jbuckner commented on packages/icon-sort-ascending/index.js
> +<svg height="18" viewBox="0 0 18 18" width="18" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="m2.32514544 8.30769231.7756949-2.08468003h2.92824822l.75630252 2.0846800
Oh, also add a `<title>` and `<desc>` for accessibility, [like this](https://github.com/internetarchive/iaux-icons/blob/master/packages/icon-calendar/index.js#L5-L6)

You can run the code formatter on this to make it easier to read.

2021-05-14 22:32 UTC, jbuckner commented on packages/icon-sort-ascending/index.js
> +<svg height="18" viewBox="0 0 18 18" width="18" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="m2.32514544 8.30769231.7756949-2.08468003h2.92824822l.75630252 2.0846800
Oh for those accessibility tags, you need to add `aria-labelledby` to the `svg` tag. See that example above.

2021-05-14 23:33 UTC, jbuckner commented on packages/icon-sort-descending/sort-descending.svg
> +  xmlns="http://www.w3.org/2000/svg"
Add a labeled by attribute to this tag:
```
aria-labelledby="sortDescendingTitleID sortDescendingDescID"
```

2021-05-15 00:00 UTC, jbuckner commented on packages/icon-sort-ascending/index.js
> +<svg height="18" viewBox="0 0 18 18" width="18" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="m2.32514544 8.30769231.7756949-2.08468003h2.92824822l.75630252 2.0846800
It looks like you made the change to the `svg` file, but not the `index.js` file

2021-05-19 00:44 UTC, dualcnhq commented
updated repo with aria-labels and updated packages

2021-05-19 16:33 UTC, jbuckner commented on packages/icon-sort-ascending/sort-ascending.svg
> +  <desc id="sortDescendingDescID">An illustration of an arrow pointing downwards from A-Z.</desc>
Your `title` and `desc` here both say "descending".. they should be "ascending"

2021-05-19 16:33 UTC, jbuckner commented on packages/icon-sort-ascending/index.js
> +  <desc id="sortDescendingDescID">An illustration of an arrow pointing downwards from A-Z.</desc>
Replace `descending` with `ascending` here

2021-05-20 15:55 UTC, jbuckner commented on packages/icon-sort-ascending/index.js
> +    <path d="m2.32514544 8.30769231.7756949-2.08468003h2.92824822l.75630252 2.08468003h1.01809955l-2.70523594-6.92307693h-1.01809955l-2.69553976 6.92307693zm3.41305753-2.86037492h-2.34647705l1.173238
I was looking at the `ia-icons` demo page and it looks like for these icons, you might need to put the `class="fill-color"` on the `<path>` tag instead of the `<g>` tag and remove the `fill="#fff"`. That `fill="#fff"` is causing it to always be white regardless of the fill-color set. Some svgs need to be treated differently depending on how it's laid out.

Normal:
<img width="274" alt="Screen Shot 2021-05-20 at 8 52 30 AM" src="https://user-images.githubusercontent.com/51138/119010481-f38fbf00-b948-11eb-920b-c1c28e50fd8e.png">

Mouseover:
<img width="226" alt="Screen Shot 2021-05-20 at 8 52 23 AM" src="https://user-images.githubusercontent.com/51138/119010502-f8547300-b948-11eb-87e0-f31293785cbc.png">

2021-05-21 17:44 UTC, dualcnhq commented on packages/icon-sort-ascending/index.js
> +    <path d="m2.32514544 8.30769231.7756949-2.08468003h2.92824822l.75630252 2.08468003h1.01809955l-2.70523594-6.92307693h-1.01809955l-2.69553976 6.92307693zm3.41305753-2.86037492h-2.34647705l1.173238
resolved and updated the commit changes preview

2021-05-26 00:43 UTC, iisa approved these changes
I think we do not save the package-lock.json files in the individual icon repos, but only in main `ia-icons`. let's update it so that it conforms then it is good

2021-05-26 00:46 UTC, merged